name = "Gym"
uuid = "b0807396-df37-52ae-a4b9-7a7124410845"
authors = ["Ozan Arkan Can <can.ozanarkan@gmail.com>"]
version = "1.1.3"

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
julia = "â‰¥ 1.0.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
